### ISSUE TITLE
ethzasl_sensor_fusion second tutorial: NAN Error

### ISSUE THREAD

**Issue by wendyhh** [ethz-asl/ethzasl_sensor_fusion#17]
Hi,

Thanks for sharing your framework. Now I try to follow the second tutorial (viconpose_sensor), but I got some problem which similar with the old issue published here (https://github.com/ethz-asl/ethzasl_sensor_fusion/issues/6), but I still can't solve this. The following is output info:
process[viconpose_sensor-1]: started with pid [11982]
[ INFO] [1381255401.020772867]: interpreting measurement as sensor w.r.t. world
[ INFO] [1381255401.020851439]: using fixed covariance
[ INFO] [1381255401.033578756]: Filter type: viconpose_sensor
[ INFO] [1381255401.033650623]: /viconpose_sensor:
    subscribed to topics:
        /auk/fcu/imu
        /ssf_core/hl_state_input
        /vicon/auk/auk
    advertised topics:
        /rosout
        /ssf_core/state_out
        /ssf_core/correction
        /ssf_core/pose
        /ssf_core/ext_state
        /viconpose_sensor/parameter_descriptions
        /viconpose_sensor/parameter_updates

[ INFO] [1381255413.846260449]: filter initialized to: 
position: [0.371229, 0.109753, 1.19432]
scale:1
attitude (w,x,y,z): [-0.432855, -0.435135, 0.364935, 0.700084]
p_ci: [0, 0, 0]
q_ci: (w,x,y,z): [1, 0, 0, 0]
q_cv: (w,x,y,z): [-0.432855, -0.435135, 0.364935, 0.700084]
q_wv: (w,x,y,z): [1, 0, 0, 0]
[ WARN] [1381255413.863853053]: large time-gap re-initializing to last state

=== ERROR ===  update: NAN at index 0
=== ERROR ===  prediction p: NAN at index 0
=== ERROR ===  update: NAN at index 0
=== ERROR ===  update: NAN at index 0
=== ERROR ===  prediction p: NAN at index 0
=== ERROR ===  update: NAN at index 0
=== ERROR ===  update: NAN at index 0
=== ERROR ===  prediction p: NAN at index 0

The related advice is "the measurement messages are not correctly received" mentioned in the old issues. But I think I have gotten the measurement messages such as:
       position: [0.371229, 0.109753, 1.19432]
       q_cv: (w,x,y,z): [-0.432855, -0.435135, 0.364935, 0.700084]

Later amajan said another problem is IMU timestamp, but I use dataset which is same as the first tutorial. I can get first tutorial working. So I don't know what's the reason?

Thanks in advance.

**Comment by stephanweiss** [comment]
Hi,

Thanks for using our framework.

In the outputs I see attitude (w,x,y,z): [-0.432855, -0.435135, 0.364935, 0.700084]. This looks odd - at least in the initial phase the attitude should be roughly gravity aligned. Do you initialize all states correctly in viconpose_measurements.h?

Best
Stephan

**Comment by wendyhh** [comment]
Thanks for your reply.
This outputs I got is the following stituation:  
rosbag play -s 25 dataset.bag
Here I haven't paused this. When initializing, already have some pose be published. So I get the above attitude and position.

If I paused bag file playing (or paused after playing 1 second )until ssf_updates initialize, I got the info like this:
process[viconpose_sensor-1]: started with pid [12627]
[ INFO] [1381264002.955853520]: interpreting measurement as sensor w.r.t. world
[ INFO] [1381264002.955932022]: using fixed covariance
[ INFO] [1381264002.967678696]: Filter type: viconpose_sensor
[ INFO] [1381264002.967779338]: /viconpose_sensor:
    subscribed to topics:
        /auk/fcu/imu
        /ssf_core/hl_state_input
        /vicon/auk/auk
    advertised topics:
        /rosout
        /ssf_core/state_out
        /ssf_core/correction
        /ssf_core/pose
        /ssf_core/ext_state
        /viconpose_sensor/parameter_descriptions
        /viconpose_sensor/parameter_updates

[ WARN] [1381264017.327335394]: No measurements received yet to initialize position - using [0 0 0]
[ WARN] [1381264017.327388404]: No measurements received yet to initialize attitude - using [1 0 0 0]
[ INFO] [1381264017.328313173]: filter initialized to: 
position: [0, 0, 0]
scale:1
attitude (w,x,y,z): [1, -0, -0, -0]
p_ci: [0, 0, 0]
q_ci: (w,x,y,z): [1, 0, 0, 0]
q_cv: (w,x,y,z): [1, 0, 0, 0]
q_wv: (w,x,y,z): [1, 0, 0, 0]

But this suitation have warning: no measurements received yet. Then I unpaused bag playing, I also get the above ERROR. 
Sometime also have the following warn:
[ WARN] [1381264083.889134493]: Negative scale detected: -6.39904. Correcting to 0.1

**Comment by stephanweiss** [comment]
You only should initialize the filter after having received some measurements.
Also, did you slow down the vicon measurements as in the previous tutorial?

if (msg->header.seq%5!=0)
  return;

Best
Stephan

**Comment by wendyhh** [comment]
I am not sure if bag file should be played when initialize the filter. Or I need first run bag file a little bit, then paused this bag and initialize filter by regconfigure_gui, then unpaused. But I try to these two ways, both I got the above error. I try to slow down the vicon measurements, still can't solve this. 
I try to output "correction_" value, I find just the first time I can get some values, such as:
  [ INFO] [1381278240.926336237]: filter initialized to: 
position: [0.0884157, -0.479283, 1.27955]
scale:1
attitude (w,x,y,z): [0.918546, 0.0576142, 0.317228, -0.228736]
p_ci: [0, 0, 0]
q_ci: (w,x,y,z): [1, 0, 0, 0]
q_cv: (w,x,y,z): [0.918546, 0.0576142, 0.317228, -0.228736]
q_wv: (w,x,y,z): [1, 0, 0, 0]
[ WARN] [1381278245.665259822]: large time-gap re-initializing to last state

[ INFO] [1381278245.700895688]: Correction:5.71485, 2.27836, -1.01377, 7.5941, 1.71769, 0.284326, 0.800916, -1.15169, 0.261218, -0.00378457, 0.0116142, -0.0068543, -1.07433, 0.99399, -0.00820217, 0.868454, 1.16619, -1.07849, 0.000329373, -0.00642569, -0.0513257, -0.039122, -0.589274, -0.753541, -1.11782

[ INFO] [1381278245.751261167]: Correction:-nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan

**Comment by stephanweiss** [comment]
have you set the playback flag to True in the fix param file?
If so, please send:
- your fix param file
- your viconpose_measurement.h
- an image showing rxgraph (check "quiet" and "all topics")

Best
Stephan

**Comment by wendyhh** [comment]
Yes, I set playback to true. See attachment.

**Comment by stephanweiss** [comment]
the attachment might not have gotten through (?)

**Comment by wendyhh** [comment]
Sorry I don't know how to send files to github. I send these files to your
email(@mavt.ethz.ch).

**Comment by stephanweiss** [comment]
Thanks for sending the files.

In your viconpose_measurement.h file I saw that you do not forward the q_wv_ value to the init function. This might simply be a typo. So either use:

 ssf_core_.initialize(p, v, q, b_w, b_a, scale, q_wv_, P, w_m, a_m, g, q_ci_, p_ci_);  // note underscore in q_wv_ since it is a member variable and the value is read from the fix param file.

or use:
q_wv = q_wv_;  // add this line
ssf_core_.initialize(p, v, q, b_w, b_a, scale, q_wv, P, w_m, a_m, g, q_ci_, p_ci_);   // this is your current line in viconpose_measurement.h

I tested the filter and it works after this modification.

Hope that helps,
Stephan

**Comment by wendyhh** [comment]
Thanks very much. Now everything is okay.

Bests,
Huan
