### ISSUE TITLE
Prediction step providing NAN as output

### ISSUE THREAD

**Issue by garimellagowtham** [ethz-asl/ethzasl_sensor_fusion#19]
Hi Everyone,
I am trying my hand at EKF for the first time after getting the position controller to work using asctec pelican with asctec_mav_framework stack and ssdk. I put up all the connections as suggested in the sfly tutorial. I am attaching an image of the connections. 

![image](https://f.cloud.github.com/assets/4968323/1626909/09dcf16c-56e9-11e3-8153-593488e2849e.png)

My main problem is that even without initializing the ekf filter using dynamic reconfigure, when I look at the output of the /fcu/ekf_state_out (the prediction output from the high level processor), I get nan in all the fields except few which are zero. I do not understand this. When I intitialize the ekf filter at this stage, it just gives me a nan error. Should I initialize the predicition step after initializing the ssf_update or something. How to get this to work?

Thanks for your help,
Gowtham.

/fcu/ekf_state_out sample output:
header: 
  seq: 946
  stamp: 
    secs: 1385503728
    nsecs: 300362825
  frame_id: ''
angular_velocity: 
  x: 0.00209439510239
  y: 0.00209439510239
  z: 0.0225147473507
linear_acceleration: 
  x: 0.15696
  y: -0.06867
  z: 9.65304
state: [nan, nan, nan, 0.0, 0.0, 0.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
flag: 1

Error from initializing filter:
=== ERROR === prediction p: NAN at index 0
=== ERROR === update NAN at index 0

**Comment by stephanweiss** [comment]
Gowtham,

Your rxgraph suggests that there are no measurements in your setup. Do you have a module providing you a position reading (e.g. GPS, Vicon, camera)? Please see this tutorial for further details: http://wiki.ros.org/ethzasl_sensor_fusion/Tutorials/getting_started

I suggest you download ethzasl_ptam (http://wiki.ros.org/ethzasl_ptam) to get a visual pose update and use the pose_sensor module to familiarize yourself with the framework.

I hope this helps.
Best,
Stephan

**Comment by simonlynen** [comment]
@garimellagowtham I assume this is resolved. If not, feel free to reopen.
