### ISSUE TITLE
fuerte "eigen" build

### ISSUE THREAD

**Issue by sesovero** [ethz-asl/ethzasl_sensor_fusion#2]
The current master branch does not build for Fuerte ROS. I had to update the code according to:http://www.ros.org/wiki/eigen
1. all the CMakelists.txt a need:

find_package(Eigen REQUIRED)
include_directories(${Eigen_INCLUDE_DIRS})

2.the manifest.xml and stack.xml need:
  rosdep name="eigen" 

instead of:
depend package="eigen"

**Comment by markusachtelik** [comment]
Hi,

thanks a lot for that! It should be already in a branch "fuerte", we just haven't merged it into master yet. The current electric compatible version will be tagged and development continues on fuerte. Will do that tomorrow.

Best, Markus
