### ISSUE TITLE
ethzasl_sensor_fusion compilation problem (on groovy)

### ISSUE THREAD

**Issue by bilelxlab** [ethz-asl/ethzasl_sensor_fusion#24]
Hello,
I am trying to install the ethzasl_sensor_fusion package to make a vision based navigation, i succeeded to install this package on my personal computer (on hydro) but i can't do it on the mastermind  (the pelican) where i have groovy installed

i have this error, can you help me please : 

asctec@mastermind:~$ rosmake ethzasl_sensor_fusion
[ rosmake ] rosmake starting...  
[ rosmake ] Packages requested are: ['ethzasl_sensor_fusion']  
[ rosmake ] Logging to directory /home/asctec/.ros/rosmake/rosmake_output-20140417-040829  
[ rosmake ] Expanded args ['ethzasl_sensor_fusion'] to:
['ssf_core', 'ssf_updates', 'sensor_fusion_comm']  
[rosmake-0] Starting >>> catkin [ make ]  
[rosmake-0] Finished <<< catkin ROS_NOBUILD in package catkin
 No Makefile in package catkin  
[rosmake-0] Starting >>> genmsg [ make ]  
[rosmake-1] Starting >>> cpp_common [ make ]  
[rosmake-3] Starting >>> rospack [ make ]  
[rosmake-2] Starting >>> rosgraph [ make ]  
[rosmake-0] Finished <<< genmsg ROS_NOBUILD in package genmsg
 No Makefile in package genmsg  
[rosmake-0] Starting >>> genlisp [ make ]  
[rosmake-1] Finished <<< cpp_common ROS_NOBUILD in package cpp_common
 No Makefile in package cpp_common  
[rosmake-2] Finished <<< rosgraph ROS_NOBUILD in package rosgraph
 No Makefile in package rosgraph  
[rosmake-3] Finished <<< rospack ROS_NOBUILD in package rospack
 No Makefile in package rospack  
[rosmake-2] Starting >>> genpy [ make ]  
[rosmake-1] Starting >>> gencpp [ make ]  
[rosmake-3] Starting >>> rostime [ make ]  
[rosmake-0] Finished <<< genlisp ROS_NOBUILD in package genlisp
 No Makefile in package genlisp  
[rosmake-0] Starting >>> roslib [ make ]  
[rosmake-2] Finished <<< genpy ROS_NOBUILD in package genpy
 No Makefile in package genpy  
[rosmake-3] Finished <<< rostime ROS_NOBUILD in package rostime
 No Makefile in package rostime  
[rosmake-3] Starting >>> roscpp_traits [ make ]  
[rosmake-2] Starting >>> roslang [ make ]  
[rosmake-0] Finished <<< roslib ROS_NOBUILD in package roslib
 No Makefile in package roslib  
[rosmake-1] Finished <<< gencpp ROS_NOBUILD in package gencpp
 No Makefile in package gencpp  
[rosmake-1] Starting >>> message_generation [ make ]  
[rosmake-0] Starting >>> rosunit [ make ]  
[rosmake-3] Finished <<< roscpp_traits ROS_NOBUILD in package roscpp_traits
 No Makefile in package roscpp_traits  
[rosmake-3] Starting >>> roscpp_serialization [ make ]  
[rosmake-2] Finished <<< roslang ROS_NOBUILD in package roslang
 No Makefile in package roslang  
[rosmake-0] Finished <<< rosunit ROS_NOBUILD in package rosunit
 No Makefile in package rosunit  
[rosmake-1] Finished <<< message_generation ROS_NOBUILD in package message_generation
 No Makefile in package message_generation  
[rosmake-2] Starting >>> rosconsole [ make ]  
[rosmake-0] Starting >>> xmlrpcpp [ make ]  
[rosmake-1] Starting >>> rosparam [ make ]  
[rosmake-3] Finished <<< roscpp_serialization ROS_NOBUILD in package roscpp_serialization
 No Makefile in package roscpp_serialization  
[rosmake-3] Starting >>> message_runtime [ make ]  
[rosmake-1] Finished <<< rosparam ROS_NOBUILD in package rosparam
 No Makefile in package rosparam  
[rosmake-0] Finished <<< xmlrpcpp ROS_NOBUILD in package xmlrpcpp
 No Makefile in package xmlrpcpp  
[rosmake-1] Starting >>> rosmaster [ make ]  
[rosmake-0] Starting >>> rosclean [ make ]  
[rosmake-2] Finished <<< rosconsole ROS_NOBUILD in package rosconsole
 No Makefile in package rosconsole  
[rosmake-3] Finished <<< message_runtime ROS_NOBUILD in package message_runtime
 No Makefile in package message_runtime  
[rosmake-3] Starting >>> std_msgs [ make ]  
[rosmake-1] Finished <<< rosmaster ROS_NOBUILD in package rosmaster
 No Makefile in package rosmaster  
[rosmake-3] Finished <<< std_msgs ROS_NOBUILD in package std_msgs
 No Makefile in package std_msgs  
[rosmake-3] Starting >>> rosgraph_msgs [ make ]  
[rosmake-0] Finished <<< rosclean ROS_NOBUILD in package rosclean
 No Makefile in package rosclean  
[rosmake-1] Starting >>> geometry_msgs [ make ]  
[rosmake-3] Finished <<< rosgraph_msgs ROS_NOBUILD in package rosgraph_msgs                                                       [ 2 Active 22/38 Complete ]
 No Makefile in package rosgraph_msgs  
[rosmake-1] Finished <<< geometry_msgs ROS_NOBUILD in package geometry_msgs
 No Makefile in package geometry_msgs  
[rosmake-3] Starting >>> roscpp [ make ]  
[rosmake-1] Starting >>> sensor_msgs [ make ]  
[rosmake-0] Starting >>> rospy [ make ]  
[rosmake-3] Finished <<< roscpp ROS_NOBUILD in package roscpp
 No Makefile in package roscpp  
[rosmake-2] Starting >>> sensor_fusion_comm [ make ]  
[rosmake-2] Finished <<< sensor_fusion_comm ROS_NOBUILD in package sensor_fusion_comm
 No Makefile in package sensor_fusion_comm  
[rosmake-1] Finished <<< sensor_msgs ROS_NOBUILD in package sensor_msgs
 No Makefile in package sensor_msgs  
[rosmake-3] Starting >>> rosout [ make ]  
[rosmake-0] Finished <<< rospy ROS_NOBUILD in package rospy
 No Makefile in package rospy  
[rosmake-3] Finished <<< rosout ROS_NOBUILD in package rosout
 No Makefile in package rosout  
[rosmake-3] Starting >>> roslaunch [ make ]  
[rosmake-3] Finished <<< roslaunch ROS_NOBUILD in package roslaunch
 No Makefile in package roslaunch  
[rosmake-3] Starting >>> rostest [ make ]  
[rosmake-3] Finished <<< rostest ROS_NOBUILD in package rostest
 No Makefile in package rostest  
[rosmake-3] Starting >>> topic_tools [ make ]  
[rosmake-3] Finished <<< topic_tools ROS_NOBUILD in package topic_tools
 No Makefile in package topic_tools  
[rosmake-3] Starting >>> rosbag [ make ]  
[rosmake-3] Finished <<< rosbag ROS_NOBUILD in package rosbag
 No Makefile in package rosbag  
[rosmake-3] Starting >>> rosmsg [ make ]  
[rosmake-3] Finished <<< rosmsg ROS_NOBUILD in package rosmsg
 No Makefile in package rosmsg  
[rosmake-3] Starting >>> rosservice [ make ]  
[rosmake-3] Finished <<< rosservice ROS_NOBUILD in package rosservice
 No Makefile in package rosservice  
[rosmake-3] Starting >>> dynamic_reconfigure [ make ]  
[rosmake-3] Finished <<< dynamic_reconfigure ROS_NOBUILD in package dynamic_reconfigure
 No Makefile in package dynamic_reconfigure  
[rosmake-3] Starting >>> ssf_core [ make ]  
[ rosmake ] All 26 linessf_core: 1.6 sec ]                                                                                        [ 1 Active 36/38 Complete ]
{-------------------------------------------------------------------------------
  mkdir -p bin
  cd build && cmake -Wdev -DCMAKE_TOOLCHAIN_FILE=/opt/ros/groovy/share/ros/core/rosbuild/rostoolchain.cmake  ..
  [rosbuild] Building package ssf_core
  [rosbuild] Cached build flags older than manifests; calling rospack to get flags
  Failed to invoke /opt/ros/groovy/bin/rospack cflags-only-I;--deps-only ssf_core
  Package sensor_fusion_comm was not found in the pkg-config search path.
  Perhaps you should add the directory containing `sensor_fusion_comm.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'sensor_fusion_comm' found
  [rospack] Error: python function 'rosdep2.rospack.call_pkg_config' could not call 'pkg-config --cflags-only-I sensor_fusion_comm' without errors

  CMake Error at /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:129 (message):

```
Failed to invoke rospack to get compile flags for package 'ssf_core'.  Look
above for errors from rospack itself.  Aborting.  Please fix the broken
dependency!
```

  Call Stack (most recent call first):
    /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:227 (rosbuild_invoke_rospack)
    CMakeLists.txt:12 (rosbuild_init)

  -- Configuring incomplete, errors occurred!
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package ssf_core written to:
[ rosmake ]    /home/asctec/.ros/rosmake/rosmake_output-20140417-040829/ssf_core/build_output.log
[rosmake-3] Finished <<< ssf_core [FAIL] [ 1.60 seconds ]  
[ rosmake ] Halting due to failure in package ssf_core. 
[ rosmake ] Waiting for other threads to complete.  
[ rosmake ] Results:  
[ rosmake ] Built 37 packages with 1 failures.  
[ rosmake ] Summary output to directory  
[ rosmake ] /home/asctec/.ros/rosmake/rosmake_output-20140417-040829  
asctec@mastermind:~$

**Comment by markusachtelik** [comment]
for some reason, you have ROS_NOBUILD in package sensor_fusion_comm

**Comment by bilelxlab** [comment]
sorry it's  realy stupide but what can be the reason markusachtelik ?

**Comment by zanazakaryaie** [comment]
Hello

How did you intalled the package on hydro version? Is there any specific instructions? The webpage has listed it only for fuerte and groovy

**Comment by bilelxlab** [comment]
ahh yes my mistake ^^ ....solved
