### ISSUE TITLE
Is it possible to use this outside of ROS?

### ISSUE THREAD

**Issue by aledalgrande** [ethz-asl/ethzasl_sensor_fusion#26]
Can I use the sensor fusion package on an independent C++ platform?

**Comment by simonlynen** [comment]
Hi @aledalgrande ,

you should use our new package: https://github.com/ethz-asl/ethzasl_msf

Here we pushed towards keeping ROS as far as possible outside the algorithm. In fact there should be very little changes required to run the EKF without ROS.

See as an example the file: https://github.com/ethz-asl/ethzasl_msf/blob/master/msf_core/include/msf_core/msf_IMUHandler.h Which can take IMU from any source. Similarly you would need to work out a sensor-handler that does not use ROS: 
https://github.com/ethz-asl/ethzasl_msf/blob/master/msf_updates/src/position_msf/position_sensormanager.h

I am happy accepting pull-requests for changes that allow an easier use without ROS.

**Comment by aledalgrande** [comment]
That is great. Do you have a tutorial for the new framework? What if I’m using a keyframe-based vision system? I’m trying to build something inspired to:  

http://cvg.ethz.ch/mobile/LiveMetric3DReconstructionICCV2013.pdf

but I’m stuck as I don’t understand:
1) when to start visual inertial fusion, considered there is a purely visual stereo initialization;
2) how to recover the transformation between IMUs and camera (given they have same orientation and position, I guess if I have Z vertical in the IMU, I’ll have to rotate to Y vertical or whatever the visual system is)

After initialization patch matching based on the (Kalman filtered) inertial pose is used to get the visual pose. But to do that you would need the (converged) scale and camera-IMU transformation. Conversely, to get the scale the visual pose is needed, but the only pose I have comes from stereo init, not the 30Hz tracker. It seems like a chicken-and-egg problem. Is there a phase of “visual-inertial” calibration before everything can start?  

Thanks--  
Alessandro Dal Grande

**Comment by simonlynen** [comment]
The new framework is in many ways similar to the old one so doing the tutorials for the old one will get you pretty far.

1) As soon as you have an update from your stereo algorithm the filter will predict your state with the IMU compute the best estimate of your pose from all sensors.
2) Start by measuring the relative transformation. The EKF will then estimate the quantity online and provide a better estimate over time. If you have stereo you don't need to estimate the scale.

**Comment by aledalgrande** [comment]
Sorry, what I meant is the stereo algorithm is used just for frames 1-2, but the system is monocular. So I think I will still need a scale estimate?
If I understand what you said, the procedure is:

stereo init with frames 1&2 -> update filter with visual pose -> get first IMU sample -> convert to visual coordinate system -> filter predict

Is that correct?  

## 

Alessandro Dal Grande

**Comment by simonlynen** [comment]
OK in this case you can read through the following papers to understand how you can build such a system: http://margaritachli.com/papers/ICRA2012_vslam_paper.pdf
http://onlinelibrary.wiley.com/doi/10.1002/rob.21466/abstract

**Comment by aledalgrande** [comment]
Thank you!

## 

Alessandro Dal Grande
