### ISSUE TITLE
Example code or API

### ISSUE THREAD

**Issue by bvibhav** [ethz-asl/ethzasl_sensor_fusion#27]
Hello,

I am not sure if i missed it somewhere while reading or not, But can someone guide to an example code to use this module.

I am trying to combine odometry from other sensor sources with IMU but can't figure out all the messages and topic I need to.

Thank you

**Comment by simonlynen** [comment]
@bivbhav There is a full set of tutorials that you can read through. http://wiki.ros.org/ethzasl_sensor_fusion/Tutorials

**Comment by bvibhav** [comment]
I went through the tutorials, I still have a concern, In any case, I will have three topics to subscribe to but the sensor fusion is supposed to work with only one prediction and one update. Also, I only understand imu_state_input, What are the other topics for?

pose_measurement (geometry_msgs/PoseWithCovarianceStamped)

```
the sensor's information source 
```

imu_state_input (sensor_msgs/Imu)

```
propagation sensor input for internal state propagation 
```

hl_state_input (sensor_fusion_comm/ExtEkf)

```
input from external state propagation (e.g. asctec_mav_framework) 
```

**Comment by stephanweiss** [comment]
Hi,

If you use multiple sensors with different time delays I recommend to use our new version of ethzasl_sensor_fusion for multiple sensor inputs:
https://github.com/ethz-asl/ethzasl_msf/wiki
If all sensors have the same timestamps you may collect them and still use ethzasl_sensor_fusion (http://wiki.ros.org/ethzasl_sensor_fusion) which might be easier to start with.

The theory to the multi-sensor fusion framework is described here (Section 3.4)
http://e-collection.library.ethz.ch/eserv/eth:5889/eth-5889-02.pdf
and a detailed implementation description can be found here:
https://github.com/ethz-asl/ethzasl_msf/raw/master/2013_IROS_lynen_modular_sensor_fusion.pdf

the messages are:
- pose_measurement: the input of your _measurement_ sensors (anything but the IMU)
- imu_state_input: your prediction input (i.e. the IMU acc and gyros)
- hl_state_input: this links to the AscTec helicopter highlevel controller and is for external state _propagation_. I.e. the message contains the IMU readings and the non-zero-propagation states position, velocity, attitude which have been propagated by your/the AscTec external module. Please see this paper for more information on propagation and update splitting of our framework:
  http://publications.asl.ethz.ch/files/weiss12versatile.pdf (for the single sensor fusion, SSF)
  http://publications.asl.ethz.ch/files/lynen13robust.pdf (for the multi sensor fusion, MSF)

Hope this helps.

Best,
Stephan
